### ISSUE TITLE
Plugin settings

### ISSUE THREAD

**Issue by thefubon** [cloudgrayau/pitch#2]
Please make a gif or the video is usually set up and where and how to put the files. Can't configure correctly (

**Comment by cloudgrayau** [comment]
I have released 1.0.3 which now includes a better README and an example directory that you can install (for working examples).

Please let me know how you go.

**Comment by thefubon** [comment]
Thanks! I really missed this plugin.

**Comment by thefubon** [comment]
I just can't figure out how to start compiling files. I added style.scss to the file, but nothing happens. https://craft.fubon.uk/pitch

**Comment by thefubon** [comment]
`test {
  color:$white;;
  &:hover {
    color:$black;
  }
}`

**Comment by cloudgrayau** [comment]
Can you update* to the latest Pitch version 1.0.3 in Craft. Then the SCSS tests in the example /pitch should work and you can go from there.

**Comment by thefubon** [comment]
Thanks, everything worked. I cannot understand how to save from the file SCSS to CSS.

**Comment by cloudgrayau** [comment]
Great, glad everything worked.

The plugin was created for on the go SCSS compiling (I have no plans to change this at the moment). Caching will however prevent the SCSS file from regenerating on each load (recommended).

If you have caching on and are after the final CSS file, you should be able to grab this from the storage directory.
