### ISSUE TITLE
craft 4 | plug in doesn't actually *compile* code

### ISSUE THREAD

**Issue by TommasoSangiorgio** [cloudgrayau/pitch#4]
hello, just installed the plug in but it doesn't actually compile code, it converts the snippet in a classic css meta tag  calling the .scss file. Am I doing something wrong? 
Also, most classes and attributes are left completely ignored.

**Comment by cloudgrayau** [comment]
Hello.

The plugin compiles and caches the SCSS on each page load by default. Did you install the example files from the "resources" directory? That is generally the best way to start to make sense of how it works.

If you enable advanced mode (and run through the documentation) it will compile the files and further bypass Pitch entirely on subsequent page loads.

I hope that helps.

**Comment by TommasoSangiorgio** [comment]
I did but I'm pretty sure that "compield" file should not be .scss 

<img width="686" alt="Screenshot 2022-05-07 at 02 33 28" src="https://user-images.githubusercontent.com/61148683/167230675-2d14b5dd-63d3-4f17-b73a-40924928ade5.png">


> Hello.
> 
> The plugin compiles and caches the SCSS on each page load by default. Did you install the example files from the "resources" directory? That is generally the best way to start to make sense of how it works.
> 
> If you enable advanced mode (and run through the documentation) it will compile the files and further bypass Pitch entirely on subsequent page loads.
> 
> I hope that helps.

**Comment by cloudgrayau** [comment]
It should read "Pitch (uncompiled)" I guess. But basically if you call the /scss/<filename>.scss, it will compile that file on the fly. If you click on both links, the original file and the compiled file you will see that Pitch is compiling the second file.

**Comment by TommasoSangiorgio** [comment]
> It should read "Pitch (uncompiled)" I guess. But basically if you call the /scss/.scss, it will compile that file on the fly. If you click on both links, the original file and the compiled file you will see that Pitch is compiling the second file.

It acts kinda weird. I couldn't use a  pre-existent scss and call it normally, I had to set a whole directory outside "public", "_settings.scss" does't work unless I set the first 5 variables exactly as it is in the example file.
Calling assets via url doesn't work properly, because it auto generate a fake path with "scss" after the first slash, considers it as the root but the directory doesn't actually exist.
I don't understand if it's just me or something important is missing from the documentation to give the plug in a better understanding.

**Comment by laurabennett** [comment]
I'm also confused. Under my public web directory I added pitchassets and and the top of my twig template 
{% do view.registerCssFile(url('pitchassets/scss/headings,style.scss')) %}
This is the output below, shouldn't it be a combined and minified file?
`<link href="http://bigpicture.cranmore.drivedev.net/pitchassets/scss/headings,style.scss" rel="stylesheet">`

**Comment by cloudgrayau** [comment]
> I'm also confused. Under my public web directory I added pitchassets and and the top of my twig template {% do view.registerCssFile(url('pitchassets/scss/headings,style.scss')) %} This is the output below, shouldn't it be a combined and minified file?

Hello Laura,

That is manually calling the file. To run it through pitch you need to prefix it with either "css OR scss", as follows:

{% do view.registerCssFile(url('**scss**/pitchassets/scss/headings,style.scss')) %}

Please let me know how you go.

**Comment by laurabennett** [comment]
Doesn't seem to make any difference. It just adds to the path.
`<link href="http://bigpicture.cranmore.drivedev.net/scss/pitchassets/scss/headings,style.scss" rel="stylesheet">`

**Comment by cloudgrayau** [comment]
> Doesn't seem to make any difference. It just adds to the path. `<link href="http://bigpicture.cranmore.drivedev.net/scss/pitchassets/scss/headings,style.scss" rel="stylesheet">`

I'm sorry to hear you are having issues. I have attempted to load that file "http://bigpicture.cranmore.drivedev.net/scss/pitchassets/scss/headings,style.scss" and it looks to be parsing through Pitch, however it seems you have your cache directory set as a http:// address so it's throwing a warning. Please disable the cache for pitch or reset the cache directory back to "@storage/pitch" and see if that helps.

**Comment by laurabennett** [comment]
That helped! Thanks
