### ISSUE TITLE
Question: Can SCSS from a field be compiled and included?

### ISSUE THREAD

**Issue by gbowne-quickbase** [cloudgrayau/pitch#5]
We're experimenting with a field for when we need specialized HTML/CSS to put something on a page that we don't have time to build out for a component or as a one-off. We'd love to allow SCSS in that field and then have the string compiled and output on page. Is that a possibility?

**Comment by cloudgrayau** [comment]
Hello Greg,

I will look at adding this in the next version. Simply a twig variable that can be used to compile SCSS and/or minify CSS or JS, for example:

`<style>{{ craft.pitch.renderSCSS(entry.field)|raw }}</style>`

You will need to have a separate field entirely for the SCSS though, as the ScssPhp library won't compile with combined HTML code.

**Comment by cloudgrayau** [comment]
This has now been released as 2.2.0.

**Comment by gbowne-quickbase** [comment]
Wow. You are awesome! That was so fast and amazing. Thanks
