### ISSUE TITLE
Cannot update to 2.2.0

### ISSUE THREAD

**Issue by proximo7** [cloudgrayau/pitch#6]
When trying to update to 2.2.0 we get a composer error:
Problem 1
- cloudgrayau/pitch 2.2.0 requires scssphp/scssphp ^1.11.30 -> found scssphp/scssphp[1.x-dev] but it does not match your minimum-stability.
- Root composer.json requires cloudgrayau/pitch 2.2.0 -> satisfiable by cloudgrayau/pitch[2.2.0].

**Comment by cloudgrayau** [comment]
Thanks!
I have fixed that in 2.2.1. Should be out shortly.
