### ISSUE TITLE
Advanced Caching Mode enabled in dev mode

### ISSUE THREAD

**Issue by tibbis** [cloudgrayau/pitch#8]
Hi,

I noticed that Advanced Caching Mode is enabled in dev mode, I don't think it is expected to do so.

**Comment by cloudgrayau** [comment]
Hello,

Advanced Caching Mode is not recommended for use in dev mode. However, it can be enabled if the developer wants to test it whilst in dev mode. You can simply disable it via the settings.

**Comment by tibbis** [comment]
Yes I know, but there is no way of enabling it only in production mode as admin changes are not allowed on live server. So pretty difficult to have it enabled on live and disabled on dev using that setting switch...

**Comment by cloudgrayau** [comment]
Hi,

You can override that behavior by creating a "pitch.php" file with the below code, and placing it in the "config" directory.

```
<?php
use craft\helpers\App;

$isDev = App::env('CRAFT_ENVIRONMENT') === 'dev';
return [
  'advancedCache' => !$isDev,
  'cacheDir' => ($isDev) ? '@storage/pitch' : '@webroot/pitch'
];
?>
